version: '3.8'

services:
  database:
    image: mysql
    volumes:
      - ./data/world/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=world
    ports:
      - 3306:3306
  
  users-database:
    image: mysql
    volumes:
      - ./data/users/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=world
    ports:
      - 3307:3306

  webserver:
    build: ./src
    depends_on:
      - database
    restart: on-failure
    command: supervisor -e '.' index.js
    environment:
      - DATABASE_HOST=database
      - USER_DATABASE_HOST=users-database
    ports:
      - 3000:3000