version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:bionic-curl
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build container
          command: docker-compose build
      - run:
          name: Run container
          command: docker-compose up -d

workflows:
  version: 2
  build:
    jobs:
      - build